apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WMS901/aws-helm-charts.git
    targetRevision: main
    path: service/user-service
  destination:
    server: https://kubernetes.default.svc
    namespace: wms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true