controller:
  service:
    type: LoadBalancer
    nodePorts:
      http: 31100  # 80 포트에 해당하는 NodePort 설정
      https: 31200 # 443 포트에 해당하는 NodePort 설정
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  config:
    use-forwarded-headers: "true"
    proxy-body-size: "50m"
    ssl-redirect: "true"
