apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.9.0
    replicas: 2  # Kafka 브로커 개수
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      log.retention.hours: 168
    storage:
      type: ephemeral  # 영구 저장 필요시 'persistent-claim'으로 변경
  zookeeper:
    replicas: 3  # Zookeeper 개수
    storage:
      type: ephemeral  # 영구 저장 필요시 'persistent-claim'으로 변경
  entityOperator:
    topicOperator: {}
    userOperator: {}

