apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: wms
  labels:
    app: user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: DB_URL
              value: "{{ .Values.env.DB_URL }}"
            - name: DB_USERNAME
              value: "{{ .Values.env.DB_USERNAME }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
            - name: DB_DRIVER
              value: "{{ .Values.env.DB_DRIVER }}"

            - name: REDIS_CLUSTER_NODES
              value: "{{ .Values.env.REDIS_CLUSTER_NODES }}"
            - name: REDIS_PORT
              value: "{{ .Values.env.REDIS_PORT }}"
            - name: REDIS_PASSWORD
              value: "{{ .Values.env.REDIS_PASSWORD }}"

