apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-inbound-pvc
  labels:
    app.kubernetes.io/name: mongo-inbound
    app.kubernetes.io/instance: mongo-inbound
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mongo-inbound
    meta.helm.sh/release-namespace: mongo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
  volumeName: mongo-inbound-pv
