replicaCount: 1

image:
  repository: chamchimayo/inventory-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1040

env:
  SERVER_PORT: 1040
  DB_URL: jdbc:postgresql://postgres-inventory.postgres:5432/wms_inventory
  DB_USERNAME: user1
  DB_PASSWORD: user1
  DB_DRIVER: org.postgresql.Driver

  # Kafka 설정 추가
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "inventory-group"
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.springframework.kafka.support.serializer.JsonDeserializer"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: "*"

  # Kafka Producer 설정 추가
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "org.springframework.kafka.support.serializer.JsonSerializer"

  SPRING_KAFKA_TOPIC_INVENTORY_UPDATED: "inventory-updated"
  SPRING_KAFKA_TOPIC_INBOUND_CONFIRMED: "inbound-confirmed-0"
  SPRING_KAFKA_PRODUCER_ACKS: "all"

