apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch
data:
  cwagentconfig.json: |
    {
      "agent": {
        "metrics_collection_interval": 60,
        "run_as_user": "cwagent",
        "region": "us-east-1",
        "debug": true
      },
      "metrics": {
        "append_dimensions": {
          "ClusterName": "wms-cluster"
        },
        "aggregation_dimensions": [
          ["ClusterName", "PodName", "Namespace"],
          ["ClusterName", "Namespace"]
        ],
        "metrics_collected": {
          "cpu": {
            "measurement": [
              "cpu_usage_idle",
              "cpu_usage_iowait",
              "cpu_usage_user",
              "cpu_usage_system"
            ],
            "metrics_collection_interval": 60,
            "resources": ["*"],
            "totalcpu": true
          },
          "mem": {
            "measurement": [
              "mem_used_percent"
            ],
            "metrics_collection_interval": 60
          },
          "kubernetes": {
            "cluster_name": "wms-cluster",
            "metrics_collection_interval": 60,
            "enhanced_container_insights": true,
            "measurement": [
              "cpu_usage_total",
              "memory_rss",
              "memory_working_set",
              "network_rx_bytes",
              "network_tx_bytes"
            ]
          }
        }
      }
    }
