postgresql:
  database: "user_db"
  username: "user1"
  password: "user1"

storage:
  size: 1Gi

service:
  type: ClusterIP
  name: postgres-user
  port: 5433

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
