apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # PVC와 자동 매칭되도록 빈 값으로 설정
  nfs:
    path: /database/redis/redis-pv-0
    server: 195.168.9.123
  claimRef:
    namespace: redis
    name: redis-data-redis-cluster-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /database/redis/redis-pv-1
    server: 195.168.9.123
  claimRef:
    namespace: redis
    name: redis-data-redis-cluster-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /database/redis/redis-pv-2
    server: 195.168.9.123
  claimRef:
    namespace: redis
    name: redis-data-redis-cluster-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /database/redis/redis-pv-3
    server: 195.168.9.123
  claimRef:
    namespace: redis
    name: redis-data-redis-cluster-3

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /database/redis/redis-pv-4
    server: 195.168.9.123
  claimRef:
    namespace: redis
    name: redis-data-redis-cluster-4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-5
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /database/redis/redis-pv-5
    server: 195.168.9.123
  claimRef:
    namespace: redis
    name: redis-data-redis-cluster-5

