apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: redis
  labels:
    app: redis
spec:
  clusterIP: None  # Headless Service 유지
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: redis-bus
      port: 16379
      targetPort: 16379
  selector:
    app: redis

