replicaCount: 1

image:
  repository: chamchimayo/user-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1041

env:
  SERVER_PORT: 1041
  DB_URL: jdbc:postgresql://postgres-user.postgres:5433/user_db
  DB_USERNAME: user1
  DB_PASSWORD: user1
  DB_DRIVER: org.postgresql.Driver
  REDIS_CLUSTER_NODES: redis-cluster-headless.redis.svc.cluster.local:6379
  REDIS_PASSWORD: YLVGtPhO7s
  REDIS_PORT: 6379
