apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-outbound
  labels:
    app: mongo-outbound
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo-outbound
  template:
    metadata:
      labels:
        app: mongo-outbound
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27018
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.env.MONGO_INITDB_ROOT_USERNAME }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.env.MONGO_INITDB_ROOT_PASSWORD }}"
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.env.MONGO_INITDB_DATABASE }}"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          command: ["mongod", "--bind_ip_all", "--port", "27018"]
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-outbound-pvc

