apiVersion: v1
kind: Service
metadata:
  name: mongo-outbound
  labels:
    app: mongo-outbound
spec:
  type: ClusterIP
  selector:
    app: mongo-outbound
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27018

